### ISSUE TITLE
TheRarBG plugin smarten up?

### ISSUE THREAD

**Issue by Pocokk** [BurningMop/qBittorrent-Search-Plugins#11]
Dear BurningMop,

I've just found Your TheRarBG plugin and it is great! However I have a little issue with it: [as you can see on the picture](https://i.imgur.com/8DlBH0O.png), the search results aren't resemble what I actually want to looking for, it lists a bunch of unrelated stuff. Can you somehow smarten it up perhaps, to not be this sensitive? 

Thank you in advance!

**Comment by BurningMop** [comment]
I'll see what can i do.

**Comment by Pocokk** [comment]
How does it look so far, could it be modified to a certain degree, to be less spam-y?

**Comment by BurningMop** [comment]
Sorry for the delay, I was busy with work. I found the issue, and we'll be pushing the code soon

**Comment by BurningMop** [comment]
I just pushed the version 1.2, and should fix the issue.

**Comment by Pocokk** [comment]
Thank you, working fine!
