### ISSUE TITLE
Search doesn't work for certain results

### ISSUE THREAD

**Issue by Josh65-2201** [BurningMop/qBittorrent-Search-Plugins#12]
## Description
I'm using the bitsearch.to site and plugin and certain result wont find anything. `"My Neighbor Totoro"` for example, but if I go to the site and search it shows 100s of results

## Steps to reproduce 
Enable the bitsearch.to plugin
Enter `"My Neighbor Totoro"` as the search term
See no results
See many results on the site https://bitsearch.to/search?q=My+Neighbor+Totoro

## Logs
[qbittorrent.log](https://github.com/BurningMop/qBittorrent-Search-Plugins/files/14952469/qbittorrent.log)

## Versions
QBittorrent: 4.6.3
Plugin: 1.0
OS: Windows 11 10.0.22621.3374

**Comment by BurningMop** [comment]
Hi, I'll take a look, if it's failing with certain search terms, it's probably related to some parsing issue.

**Comment by BurningMop** [comment]
Version 1.1 has been pushed, and this issue it's fixed.

**Comment by chandujr** [comment]
Hi, this is still an issue. I have qBittorrent v5.1.2 and Python v3.13.5. I'm on Nobara Linux 42. Is the Python version causing the issue. Because I saw you mentioned that it is compatible with v3.9.x. Do I have to install that version?
